const lessons=[
{title:'Prima di credere, verifica',time:'15 min',sub:'Perché è importante non confondere una frase plausibile con un fatto verificato.',body:`<p>Ogni giorno riceviamo informazioni da giornali, social network, siti internet, video e sistemi di intelligenza artificiale. Molte possono essere presentate in modo convincente, ma non tutte sono verificate.</p><p>Il primo passo del Bottino Method è distinguere ciò che una fonte <b>afferma</b> da ciò che possiamo realmente considerare un <b>fatto verificato</b>.</p><div class="callouts"><div class="principle"><b>Principio del metodo</b><br>Una frase plausibile non è necessariamente un fatto verificato.</div><div class="warning"><b>Attenzione</b><br>Non trasformare automaticamente un’affermazione riportata da una fonte in un fatto.</div></div>`},
{title:'Fatto, affermazione, fonte e interpretazione',time:'20 min',sub:'Quattro elementi che sembrano simili, ma che non devono essere confusi.',body:`<p>Quando analizziamo un’informazione dobbiamo separare quattro livelli. Questa distinzione evita che una conclusione diventi più forte delle prove che possediamo.</p><div class="conceptgrid"><div><b>Fatto</b><span>Un elemento che possiamo sostenere sulla base di evidenze verificabili.</span></div><div><b>Affermazione</b><span>Ciò che una persona, un documento, un sito o un sistema dichiara.</span></div><div><b>Fonte</b><span>L’origine identificabile dalla quale proviene l’informazione.</span></div><div><b>Interpretazione</b><span>Il significato che attribuiamo agli elementi disponibili.</span></div></div><h3>Un esempio semplice</h3><p>Una persona dichiara: «Ero a Roma quel giorno». La frase è un’<b>affermazione</b>. La persona è la <b>fonte</b> di quell’affermazione. Un biglietto ferroviario, una registrazione o altri riscontri possono contribuire alla verifica. Concludere che la persona fosse certamente a Roma è invece un passaggio ulteriore, che richiede evidenze sufficienti.</p><div class="principle"><b>Regola operativa</b><br>Non promuovere un’affermazione al livello di fatto soltanto perché appare precisa, credibile o viene ripetuta.</div><h3>La stessa regola vale per l’intelligenza artificiale</h3><p>Una risposta dell’IA è un contenuto prodotto dal sistema. La fluidità del linguaggio non certifica l’origine né la correttezza dell’informazione. Prima di utilizzarla come base di una conclusione, dobbiamo poter risalire a fonti ed evidenze controllabili.</p><div class="warning"><b>Domanda di controllo</b><br>Sto descrivendo ciò che la fonte afferma, oppure sto già aggiungendo una mia interpretazione?</div>`}
];
const titles=['Prima di credere, verifica','Fatto, affermazione, fonte e interpretazione','Quanto possiamo realmente affermare?','Una fonte non vale l’altra','Quando le fonti non concordano','Il Bottino Method in pratica','Intelligenza artificiale sotto controllo','Caso finale'];
let done=Number(localStorage.getItem('bm_done')||0), current=Math.min(done,1);
function render(){
 document.querySelector('#units').innerHTML=titles.map((t,i)=>'<div class="unit '+(i<done?'done':'')+' '+(i<=1?'available':'locked')+'" data-i="'+i+'"><span class="num">0'+(i+1)+'</span><h3>'+t+'</h3><small>'+(i<done?'✓ Completata':i===done?'● Da continuare':'○ '+(i<=1?'Da iniziare':'Prossimamente'))+'</small><b>'+(i===0?'15':i===1?'20':i===7?'30':'25')+' min</b></div>').join('');
 let p=Math.round(done/8*100); document.querySelector('#pct').textContent=p+'%'; document.querySelector('#bar').style.width=p+'%';
 let n=Math.min(done,7); document.querySelector('#nextTitle').textContent='Unità '+(n+1)+' — '+titles[n];
 document.querySelectorAll('.unit.available').forEach(x=>x.onclick=()=>openLesson(Number(x.dataset.i)));
}
function openLesson(i){
 if(i>1)return; current=i; const l=lessons[i];
 document.querySelector('#lessonArticle').innerHTML='<p class="eyebrow">UNITÀ '+(i+1)+' DI 8 · '+l.time.toUpperCase()+'</p><h2>'+l.title+'</h2><p class="subtitle">'+l.sub+'</p>'+l.body+'<button class="primary" id="complete">Completa unità '+(i+1)+' →</button>';
 document.querySelector('#side').innerHTML=titles.map((t,j)=>'<small class="'+(j===i?'activeSide':'')+'">'+(j+1).toString().padStart(2,'0')+'　'+t+(j<done?'　✓':'')+'</small>').join('');
 document.querySelector('#complete').onclick=completeLesson; document.querySelector('#lesson').scrollIntoView({behavior:'smooth'});
}
function completeLesson(){
 if(current===0){done=Math.max(done,1);localStorage.setItem('bm_done',done);render();document.querySelector('#quiz').scrollIntoView({behavior:'smooth'});}
 else {done=Math.max(done,2);localStorage.setItem('bm_done',done);render();document.querySelector('#dashboard').scrollIntoView({behavior:'smooth'});}
}
render();openLesson(current);
document.querySelector('#continueCourse').onclick=()=>openLesson(Math.min(done,1));
document.querySelector('#login').onclick=()=>alert('Accesso Google: integrazione backend in preparazione. Questa demo non raccoglie credenziali.');
const opts=['Il castello fu costruito nel 1427.','Il documento dimostra che il castello fu costruito nel 1427.','Il sito afferma che un documento daterebbe la costruzione del castello al 1427.','La notizia è falsa perché il documento non è disponibile.'];
document.querySelector('#answers').innerHTML=opts.map((x,i)=>'<button data-i="'+i+'">'+String.fromCharCode(65+i)+'. '+x+'</button>').join('');
document.querySelectorAll('#answers button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#answers button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');let ok=Number(b.dataset.i)===2,f=document.querySelector('#feedback');f.className=ok?'ok':'bad';f.innerHTML=ok?'<b>Risposta corretta.</b><br>Hai mantenuto separata l’affermazione del sito dal fatto ancora da verificare.':'<b>Da rivedere.</b><br>Non abbiamo elementi per trasformare la notizia in fatto, ma neppure per dichiararla falsa.';document.querySelector('#quizNext').style.display=ok?'inline-block':'none'});
document.querySelector('#quizNext').onclick=()=>{localStorage.setItem('bm_quiz1','passed');done=Math.max(done,1);localStorage.setItem('bm_done',done);render();openLesson(1)};